### ISSUE TITLE
[BUG] magnifyingglass crashes server

### ISSUE THREAD

**Issue by Danielxs01** [LandOfRails/LandOfSignals#127]
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/30/23 5:38 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/lwjgl/opengl/GL11
	at cam72cam.mod.render.OpenGL.matrix(OpenGL.java:36)
	at net.landofrails.landofsignals.utils.HighlightingUtil.renderHighlighting(HighlightingUtil.java:32)
	at net.landofrails.landofsignals.items.ItemMagnifyingGlass.onClickBlock(ItemMagnifyingGlass.java:32)
	at cam72cam.mod.item.CustomItem$ItemInternal.func_77648_a(CustomItem.java:112)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:164)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:498)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.GL11
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
```

**Comment by Danielxs01** [comment]
Fixed with version 1.2.0
