### ISSUE TITLE
Mod crashes on load when trying to register stellwand renderers in 1.16.x

### ISSUE THREAD

**Issue by Danielxs01** [LandOfRails/LandOfSignals#5]
Mod crashes when loading umc renderer on SETUP in 1.16.x

Error:
> [23:11:36] [Worker-Main-14/INFO] [ca.mo.ModCore/]: Preparing Filler..
FATAL ERROR in native method: Thread[Worker-Main-14,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglGetIntegerv(Native Method)
	at org.lwjgl.opengl.GL11C.glGetInteger(GL11C.java:852)
	at org.lwjgl.opengl.GL11.glGetInteger(GL11.java:2673)
	at cam72cam.mod.render.obj.OBJTextureSheet.<init>(OBJTextureSheet.java:111)
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:36)
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:27)
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:23)
	at net.landofrails.stellwand.content.entities.storage.BlockFillerStorageEntity.prepare(BlockFillerStorageEntity.java:62)
	at net.landofrails.stellwand.Stellwand.clientEvent(Stellwand.java:69)

**Comment by Danielxs01** [comment]
done
